services:
  api:
    build: .
    image: nua-back-image
    container_name: nua-back-api
    tty: true

    environment:
      DATABASE_URL: postgresql+asyncpg://nua:nua@db:5432/nua
      HOST: 0.0.0.0
      PORT: 8000
      CORS_ORIGINS: "*"
      LOG_FILE: latest.log

    ports:
      - 8000:8000

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    container_name: nua-back-db

    environment:
      POSTGRES_USER: nua
      POSTGRES_PASSWORD: nua
      POSTGRES_DB: nua

    volumes:
      - nua-db-data:/var/lib/postgresql/data

    ports:
      - 5432:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nua"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  nua-db-data:
